# coding: utf-8

"""
    Salesforce Schema Deployer API

    API for extracting, managing, and deploying Salesforce metadata schemas. This API enables seamless management of Salesforce configurations across environments.

    The version of the OpenAPI document: 0.1.0
    Contact: your.email@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DeploymentRequestOptions(BaseModel):
    """
    DeploymentRequestOptions
    """ # noqa: E501
    check_only: Optional[StrictBool] = Field(default=False, description="Validate but don't deploy", alias="checkOnly")
    ignore_warnings: Optional[StrictBool] = Field(default=False, description="Ignore validation warnings", alias="ignoreWarnings")
    run_tests: Optional[StrictBool] = Field(default=False, description="Run specified tests", alias="runTests")
    test_level: Optional[StrictStr] = Field(default='NoTestRun', alias="testLevel")
    rollback_on_error: Optional[StrictBool] = Field(default=True, description="Roll back on error", alias="rollbackOnError")
    purge_on_delete: Optional[StrictBool] = Field(default=False, description="Purge on delete", alias="purgeOnDelete")
    auto_update_package: Optional[StrictBool] = Field(default=False, description="Auto-update package", alias="autoUpdatePackage")
    __properties: ClassVar[List[str]] = ["checkOnly", "ignoreWarnings", "runTests", "testLevel", "rollbackOnError", "purgeOnDelete", "autoUpdatePackage"]

    @field_validator('test_level')
    def test_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('NoTestRun', 'RunSpecifiedTests', 'RunLocalTests', 'RunAllTestsInOrg',):
            raise ValueError("must be one of enum values ('NoTestRun', 'RunSpecifiedTests', 'RunLocalTests', 'RunAllTestsInOrg')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeploymentRequestOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DeploymentRequestOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checkOnly": obj.get("checkOnly") if obj.get("checkOnly") is not None else False,
            "ignoreWarnings": obj.get("ignoreWarnings") if obj.get("ignoreWarnings") is not None else False,
            "runTests": obj.get("runTests") if obj.get("runTests") is not None else False,
            "testLevel": obj.get("testLevel") if obj.get("testLevel") is not None else 'NoTestRun',
            "rollbackOnError": obj.get("rollbackOnError") if obj.get("rollbackOnError") is not None else True,
            "purgeOnDelete": obj.get("purgeOnDelete") if obj.get("purgeOnDelete") is not None else False,
            "autoUpdatePackage": obj.get("autoUpdatePackage") if obj.get("autoUpdatePackage") is not None else False
        })
        return _obj


