# coding: utf-8

"""
    Salesforce Schema Deployer API

    API for extracting, managing, and deploying Salesforce metadata schemas. This API enables seamless management of Salesforce configurations across environments.

    The version of the OpenAPI document: 0.1.0
    Contact: your.email@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from src.models.deployment_status_results import DeploymentStatusResults
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DeploymentStatus(BaseModel):
    """
    DeploymentStatus
    """ # noqa: E501
    deployment_id: StrictStr = Field(description="Deployment ID", alias="deploymentId")
    status: StrictStr = Field(description="Deployment status")
    progress: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="Progress percentage")
    start_time: Optional[datetime] = Field(default=None, description="Deployment start time", alias="startTime")
    end_time: Optional[datetime] = Field(default=None, description="Deployment end time", alias="endTime")
    message: Optional[StrictStr] = Field(default=None, description="Additional information")
    results: Optional[DeploymentStatusResults] = None
    __properties: ClassVar[List[str]] = ["deploymentId", "status", "progress", "startTime", "endTime", "message", "results"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('queued', 'in_progress', 'completed', 'failed', 'cancelled',):
            raise ValueError("must be one of enum values ('queued', 'in_progress', 'completed', 'failed', 'cancelled')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeploymentStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of results
        if self.results:
            _dict['results'] = self.results.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DeploymentStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deploymentId": obj.get("deploymentId"),
            "status": obj.get("status"),
            "progress": obj.get("progress"),
            "startTime": obj.get("startTime"),
            "endTime": obj.get("endTime"),
            "message": obj.get("message"),
            "results": DeploymentStatusResults.from_dict(obj.get("results")) if obj.get("results") is not None else None
        })
        return _obj


