# coding: utf-8

"""
    Salesforce Schema Deployer API

    API for extracting, managing, and deploying Salesforce metadata schemas. This API enables seamless management of Salesforce configurations across environments.

    The version of the OpenAPI document: 0.1.0
    Contact: your.email@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FieldMetadata(BaseModel):
    """
    FieldMetadata
    """ # noqa: E501
    name: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    length: Optional[StrictInt] = None
    required: Optional[StrictBool] = None
    unique: Optional[StrictBool] = None
    external_id: Optional[StrictBool] = Field(default=None, alias="externalId")
    description: Optional[StrictStr] = None
    default_value: Optional[StrictStr] = Field(default=None, alias="defaultValue")
    formula: Optional[StrictStr] = None
    reference_to: Optional[StrictStr] = Field(default=None, alias="referenceTo")
    relationship_name: Optional[StrictStr] = Field(default=None, alias="relationshipName")
    __properties: ClassVar[List[str]] = ["name", "label", "type", "length", "required", "unique", "externalId", "description", "defaultValue", "formula", "referenceTo", "relationshipName"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FieldMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FieldMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "label": obj.get("label"),
            "type": obj.get("type"),
            "length": obj.get("length"),
            "required": obj.get("required"),
            "unique": obj.get("unique"),
            "externalId": obj.get("externalId"),
            "description": obj.get("description"),
            "defaultValue": obj.get("defaultValue"),
            "formula": obj.get("formula"),
            "referenceTo": obj.get("referenceTo"),
            "relationshipName": obj.get("relationshipName")
        })
        return _obj


