# coding: utf-8

"""
    Salesforce Schema Deployer API

    API for extracting, managing, and deploying Salesforce metadata schemas. This API enables seamless management of Salesforce configurations across environments.

    The version of the OpenAPI document: 0.1.0
    Contact: your.email@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from src.models.field_metadata import FieldMetadata
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ObjectMetadata(BaseModel):
    """
    ObjectMetadata
    """ # noqa: E501
    name: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    custom: Optional[StrictBool] = None
    fields: Optional[Dict[str, FieldMetadata]] = None
    description: Optional[StrictStr] = None
    sharing_model: Optional[StrictStr] = Field(default=None, alias="sharingModel")
    name_field: Optional[StrictStr] = Field(default=None, alias="nameField")
    __properties: ClassVar[List[str]] = ["name", "label", "custom", "fields", "description", "sharingModel", "nameField"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ObjectMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in fields (dict)
        _field_dict = {}
        if self.fields:
            for _key in self.fields:
                if self.fields[_key]:
                    _field_dict[_key] = self.fields[_key].to_dict()
            _dict['fields'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ObjectMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "label": obj.get("label"),
            "custom": obj.get("custom"),
            "fields": dict(
                (_k, FieldMetadata.from_dict(_v))
                for _k, _v in obj.get("fields").items()
            )
            if obj.get("fields") is not None
            else None,
            "description": obj.get("description"),
            "sharingModel": obj.get("sharingModel"),
            "nameField": obj.get("nameField")
        })
        return _obj


