# coding: utf-8

"""
    Salesforce Schema Deployer API

    API for extracting, managing, and deploying Salesforce metadata schemas. This API enables seamless management of Salesforce configurations across environments.

    The version of the OpenAPI document: 0.1.0
    Contact: your.email@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from src.models.model_schema import ModelSchema
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SchemaValidationRequest(BaseModel):
    """
    SchemaValidationRequest
    """ # noqa: E501
    var_schema: Optional[ModelSchema] = Field(default=None, alias="schema")
    schema_id: Optional[StrictStr] = Field(default=None, description="ID of the schema to validate (alternative to providing the full schema)", alias="schemaId")
    target_org_id: Optional[StrictStr] = Field(default=None, description="ID of the target organization to validate against (optional)", alias="targetOrgId")
    check_dependencies: Optional[StrictBool] = Field(default=True, description="Whether to check dependencies", alias="checkDependencies")
    strict_validation: Optional[StrictBool] = Field(default=False, description="Whether to perform strict validation", alias="strictValidation")
    __properties: ClassVar[List[str]] = ["schema", "schemaId", "targetOrgId", "checkDependencies", "strictValidation"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SchemaValidationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SchemaValidationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schema": ModelSchema.from_dict(obj.get("schema")) if obj.get("schema") is not None else None,
            "schemaId": obj.get("schemaId"),
            "targetOrgId": obj.get("targetOrgId"),
            "checkDependencies": obj.get("checkDependencies") if obj.get("checkDependencies") is not None else True,
            "strictValidation": obj.get("strictValidation") if obj.get("strictValidation") is not None else False
        })
        return _obj


