# coding: utf-8

"""
    Salesforce Schema Deployer API

    API for extracting, managing, and deploying Salesforce metadata schemas. This API enables seamless management of Salesforce configurations across environments.

    The version of the OpenAPI document: 0.1.0
    Contact: your.email@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from src.models.dashboard_metadata import DashboardMetadata
from src.models.flow_metadata import FlowMetadata
from src.models.object_metadata import ObjectMetadata
from src.models.workflow_metadata import WorkflowMetadata
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SchemaComponents(BaseModel):
    """
    SchemaComponents
    """ # noqa: E501
    objects: Optional[Dict[str, ObjectMetadata]] = None
    workflow_rules: Optional[Dict[str, WorkflowMetadata]] = Field(default=None, alias="workflowRules")
    dashboards: Optional[Dict[str, DashboardMetadata]] = None
    flows: Optional[Dict[str, FlowMetadata]] = None
    __properties: ClassVar[List[str]] = ["objects", "workflowRules", "dashboards", "flows"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SchemaComponents from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in objects (dict)
        _field_dict = {}
        if self.objects:
            for _key in self.objects:
                if self.objects[_key]:
                    _field_dict[_key] = self.objects[_key].to_dict()
            _dict['objects'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in workflow_rules (dict)
        _field_dict = {}
        if self.workflow_rules:
            for _key in self.workflow_rules:
                if self.workflow_rules[_key]:
                    _field_dict[_key] = self.workflow_rules[_key].to_dict()
            _dict['workflowRules'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in dashboards (dict)
        _field_dict = {}
        if self.dashboards:
            for _key in self.dashboards:
                if self.dashboards[_key]:
                    _field_dict[_key] = self.dashboards[_key].to_dict()
            _dict['dashboards'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in flows (dict)
        _field_dict = {}
        if self.flows:
            for _key in self.flows:
                if self.flows[_key]:
                    _field_dict[_key] = self.flows[_key].to_dict()
            _dict['flows'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SchemaComponents from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "objects": dict(
                (_k, ObjectMetadata.from_dict(_v))
                for _k, _v in obj.get("objects").items()
            )
            if obj.get("objects") is not None
            else None,
            "workflowRules": dict(
                (_k, WorkflowMetadata.from_dict(_v))
                for _k, _v in obj.get("workflowRules").items()
            )
            if obj.get("workflowRules") is not None
            else None,
            "dashboards": dict(
                (_k, DashboardMetadata.from_dict(_v))
                for _k, _v in obj.get("dashboards").items()
            )
            if obj.get("dashboards") is not None
            else None,
            "flows": dict(
                (_k, FlowMetadata.from_dict(_v))
                for _k, _v in obj.get("flows").items()
            )
            if obj.get("flows") is not None
            else None
        })
        return _obj


