# coding: utf-8

"""
    Salesforce Schema Deployer API

    API for extracting, managing, and deploying Salesforce metadata schemas. This API enables seamless management of Salesforce configurations across environments.

    The version of the OpenAPI document: 0.1.0
    Contact: your.email@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SchemaExtractionRequest(BaseModel):
    """
    SchemaExtractionRequest
    """ # noqa: E501
    org_id: StrictStr = Field(description="ID of the organization to extract schema from", alias="orgId")
    components: Optional[List[StrictStr]] = Field(default=None, description="List of components to extract. If not provided, all components will be extracted.")
    include_standard: Optional[StrictBool] = Field(default=False, description="Whether to include standard objects", alias="includeStandard")
    include_managed: Optional[StrictBool] = Field(default=False, description="Whether to include managed package components", alias="includeManaged")
    filter: Optional[StrictStr] = Field(default=None, description="Filter expression to limit extracted components")
    __properties: ClassVar[List[str]] = ["orgId", "components", "includeStandard", "includeManaged", "filter"]

    @field_validator('components')
    def components_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in ('objects', 'fields', 'workflows', 'dashboards', 'flows',):
                raise ValueError("each list item must be one of ('objects', 'fields', 'workflows', 'dashboards', 'flows')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SchemaExtractionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SchemaExtractionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orgId": obj.get("orgId"),
            "components": obj.get("components"),
            "includeStandard": obj.get("includeStandard") if obj.get("includeStandard") is not None else False,
            "includeManaged": obj.get("includeManaged") if obj.get("includeManaged") is not None else False,
            "filter": obj.get("filter")
        })
        return _obj


