# coding: utf-8

"""
    Salesforce Schema Deployer API

    API for extracting, managing, and deploying Salesforce metadata schemas. This API enables seamless management of Salesforce configurations across environments.

    The version of the OpenAPI document: 0.1.0
    Contact: your.email@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

# Fix these imports to use the correct paths after your reorganization
from src.api.routes.authentication_api import router as AuthenticationApiRouter
from src.api.routes.deployment_api import router as DeploymentApiRouter
from src.api.routes.metadata_api import router as MetadataApiRouter
from src.api.routes.organizations_api import router as OrganizationsApiRouter
from src.api.routes.schemas_api import router as SchemasApiRouter
from src.api.routes.validation_api import router as ValidationApiRouter

# Remove this circular import
# from src.api.app import app as application  <-- REMOVE THIS LINE

app = FastAPI(
    title="Salesforce Schema Deployer API",
    description="API for extracting, managing, and deploying Salesforce metadata schemas. This API enables seamless management of Salesforce configurations across environments.",
    version="0.1.0",
)

app.include_router(AuthenticationApiRouter)
app.include_router(DeploymentApiRouter)
app.include_router(MetadataApiRouter)
app.include_router(OrganizationsApiRouter)
app.include_router(SchemasApiRouter)
app.include_router(ValidationApiRouter)
